### ISSUE TITLE
add InGame UI

### ISSUE THREAD

**Issue by Razvangt** [MadCrabsTeam/mad_crabs#12]

**Comment by Razvangt** [comment]
# Player Ui

**Comment by Razvangt** [comment]
# Level up UI

**Comment by Razvangt** [comment]
![image](https://user-images.githubusercontent.com/64218714/229364593-21ceb9f8-a33d-4356-a888-fce1e723ee3e.png)

**Comment by septum** [comment]
I'll give it a go at this

**Comment by Razvangt** [comment]
- Button ui
 - Exp Bar ui
 - Walls ui
 - Abilty ui
